# Generated by Django 4.0.5 on 2022-06-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter_api', '0002_alter_comment_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='tweet', to='tweeter_api.tweets'),
        ),
    ]
