# Generated by Django 4.0.5 on 2022-06-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter_api', '0004_alter_comment_tweet_alter_like_or_dislike_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tweeter_api.tweets'),
        ),
    ]
