# Generated by Django 4.0.5 on 2022-07-01 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeter_api', '0007_alter_tweets_created_by_usersandtweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
