# Generated by Django 4.0.5 on 2022-07-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter_api', '0008_alter_tweets_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAndTweets',
        ),
    ]
